version: 0.2

phases:
  install:
    commands:
      - echo Installing K6 ...
      - curl https://github.com/loadimpact/k6/releases/download/v0.29.0/k6-v0.29.0-linux64.tar.gz -L | tar xvz --strip-components 1

  build:
    commands:
      #      Scripts env parameters are
      #      - URL
      #      - MAX_P95_MS
      #      - MAX_FAILED_RATE
      - echo "Test started with URL=$URL , MAX_P95_MS=$MAX_P95_MS, MAX_FAILED_RATE=$MAX_FAILED_RATE"
      - ./k6 run test-api.js
  post_build:
    commands:
      - echo Tests completed on `date`
